"""Amplitude-modulated Pseudo-Random Binary Signal (APRBS) sampler.

This module provides a sampler that generates piecewise-constant input
trajectories for system identification and data-driven surrogate modeling.
At each time step, a new input value is drawn with probability 0.5 once the
minimum hold duration has elapsed, producing an APRBS excitation signal that
covers the admissible input space uniformly.
"""

from dataclasses import dataclass
import numpy as np

@dataclass
class APRBS_Sampler:
    """Sampler for APRBS input trajectories.

    Generates piecewise-constant, uniformly distributed input signals over a
    specified admissible region. The signal switches to a new random value with
    probability 0.5 at each step after the minimum hold time has elapsed. Two
    usage modes are supported: step-by-step sampling via :meth:`sample` and
    batch trajectory generation via :meth:`sample_trajectory`.

    Attributes
    ----------
    u_min : np.ndarray
        Lower bounds of the admissible input region, shape ``(n_inputs,)``.
    u_max : np.ndarray
        Upper bounds of the admissible input region, shape ``(n_inputs,)``.
    min_hold_time : float
        Minimum duration (in time units) for which each input value is held
        constant before a switch can occur. Default is ``1.0``.
    max_batch_time : float
        Total duration (in time units) of a trajectory generated by
        :meth:`sample_trajectory`. Default is ``100.0``.
    delta_t : float
        Discrete time step size (in time units). Default is ``1.0``.
    seed : int or None
        Base seed for the random number generators. Two independent child
        seeds are derived via ``np.random.SeedSequence``, ensuring
        reproducibility while maintaining independence between the
        hold-time and input-value streams. If ``None``, both streams are
        seeded non-deterministically.
    """

    u_min: np.ndarray = None
    u_max: np.ndarray = None

    min_hold_time: float = 1.0
    max_batch_time: float = 100.0
    delta_t: float = 1.0
    seed: int = None

    def __init__(self, **kwargs):
        """Initialize the APRBS sampler.

        Parameters
        ----------
        **kwargs
            Keyword arguments corresponding to the dataclass fields:
            ``u_min``, ``u_max``, ``min_hold_time``, ``max_batch_time``,
            ``delta_t``, and ``seed``. All fields must be provided; no
            defaults are validated here beyond those defined in the dataclass.

        Notes
        -----
        Two independent RNG streams are derived from ``seed`` via
        ``np.random.SeedSequence``: one governing switching decisions and one
        governing input value draws. The initial input value is sampled
        immediately on construction.
        """
        for key, value in kwargs.items():
            setattr(self, key, value)

        seed_sequence = np.random.SeedSequence(self.seed)
        hold_time_seed, u_seed = seed_sequence.spawn(2)
        self.hold_time_rng = np.random.default_rng(hold_time_seed)
        self.u_rng = np.random.default_rng(u_seed)

        self.steps_in_min_hold_time = int(self.min_hold_time // self.delta_t)
        self.steps: int = 1

        self.u_old = self.u_rng.uniform(low=self.u_min, high=self.u_max)

    def sample(self) -> np.ndarray:
        """Return the input value for the current time step.

        A switch to a new uniformly distributed input is attempted with
        probability 0.5 once :attr:`min_hold_time` has elapsed since the last
        switch. If no switch occurs, the previous value is held.

        Returns
        -------
        np.ndarray
            Current input vector, shape ``(n_inputs,)``.
        """
        switch_bool: bool = False
        if self.steps >= self.steps_in_min_hold_time:
            switch_bool = (self.hold_time_rng.random() < 0.5)


        u = self.u_old
        if switch_bool:
            u = self.u_rng.uniform(low=self.u_min, high=self.u_max)
            self.steps = 0
            self.u_old = u

        self.steps += 1

        return u
    
    def sample_trajectory(self) -> np.ndarray:
        """Generate a complete APRBS trajectory over :attr:`max_batch_time`.

        The trajectory is constructed in a vectorised manner: switching
        decisions are drawn for all steps simultaneously, and input values
        are forward-filled from the last active switch index.

        Returns
        -------
        np.ndarray
            Input trajectory, shape ``(n_steps, n_inputs)``, where
            ``n_steps = int(max_batch_time / delta_t)``.
        """
        n_steps = int(self.max_batch_time // self.delta_t)
        hold_time_bool = self.hold_time_rng.random(size=n_steps) < 0.5
        u_trajectory = self.u_rng.uniform(low=self.u_min, high=self.u_max, size=(n_steps, len(self.u_min)))
                    
        # Create a mask for when to switch inputs
        switch_indices = np.where(~hold_time_bool)[0]
        
        # Forward fill: use current value until next switch
        u_trajectory_test = u_trajectory[switch_indices[np.searchsorted(switch_indices, np.arange(n_steps), side='right') - 1]]

        return u_trajectory_test
    



if __name__ == "__main__":
    sampler = APRBS_Sampler(
        u_min = np.array([0.0, 0.0]),
        u_max = np.array([1.0, 1.0]),
        min_hold_time = 1.0,
        max_batch_time = 100.0,
        delta_t = 1.0,
        seed = 42
    )

    u_aprbs = sampler.sample()
    print(u_aprbs)

    u_aprbs_traj = sampler.sample_trajectory()
    print(u_aprbs_traj)